### ISSUE TITLE
v8 - redirects created with one domain don't work with another

### ISSUE THREAD

**Issue by cmo-web** [dawoe/umbraco-redirectsviewer#21]
Hi, 

We are using the umbraco 8 version and have created a large amount of redirects logged in using one domain. When we add another domain and log in again using that, redirects don't work with the new domain - only with the old domain where the redirects were created. If we recreate the redirects again (one-by-one) logged in with the new domain, they work again, and we can then delete the old redirect. But sure there must be an easier solution to this problem?

**Comment by dawoe** [comment]
Hi @cmo-web 

Thanks for reporting this issue.

First of all what version of the package and Umbraco are you using ?

Can you try to reproduce this without using package.

So rename a item with the old domain. Check if a redirect is created by umbraco because of the renaming (through the dashboard or my package). Than remove the domain and add the new one. Does the automatic redirect still work ?

Can you also look  in the umbracoRedirects table if the domain name is included there in the url.

Dave

**Comment by cmo-web** [comment]
Thanks for your quick answer - and sorry for my slow one ;). I think we solved this issue for now by recreating all the redirects - might be a user related error somehow.
